import type { ListingSeed } from "./listing-seed";

/**
 * 25 sale listings.
 *
 * Anchored to 2026 reporting on Addis sale prices: roughly 220,000-450,000 ETB
 * per square metre in prime Bole and Old Airport, 220,000-380,000 in Kazanchis,
 * 85,000-220,000 in CMC and Summit, and 80,000-150,000 in the outer zones like
 * Jemo, Lebu, Kolfe and Akaky. G+1 houses start around 18M and luxury villas
 * pass 75M. Every price below is consistent with the size and area quoted.
 */
export const SALE_LISTINGS: ListingSeed[] = [
  // ---------------------------------------------------------------- Condominiums
  {
    ref: "BT-2001",
    lister: "abebe",
    listingType: "FOR_SALE",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom 40/60 condo for sale, CMC",
    titleAm: "ባለ ሁለት መኝታ ኮንዶሚኒየም ለሽያጭ፣ ሲኤምሲ",
    descriptionEn:
      "Eighty-four square metres on the third floor, fully paid up and the title deed is ready to transfer. I bought it in the 40/60 draw and finished it myself, so the kitchen and the bathroom are better than the standard handover. Selling because I am moving to Adama.",
    price: 9800000,
    negotiable: true,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 84,
    furnishing: "UNFURNISHED",
    area: "cmc",
    addressNote: "CMC 40/60 site, block 9",
    amenities: ["water-tank", "parking", "gated-compound", "security-guard", "electricity-meter", "water-meter", "furnished-kitchen"],
    photos: ["block", "living", "kitchen", "bedroom"],
    confirmedDaysAgo: 4,
    createdDaysAgo: 16,
    views: 892,
    contactReveals: 63,
  },
  {
    ref: "BT-2002",
    lister: "dawit",
    listingType: "FOR_SALE",
    propertyType: "CONDOMINIUM",
    titleEn: "Three-bedroom condo for sale, Summit",
    descriptionEn:
      "One hundred and eight square metres, fifth floor, lift in the building. Summit has been building out for years and this block is one of the finished ones, with a working generator and a compound that is actually maintained. Deed clean, no outstanding lease payments.",
    price: 14500000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 108,
    furnishing: "UNFURNISHED",
    area: "summit",
    addressNote: "Summit, near the Safari junction",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "balcony", "electricity-meter"],
    photos: ["block", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 9,
    createdDaysAgo: 21,
    views: 604,
    contactReveals: 41,
  },
  {
    ref: "BT-2003",
    lister: "hanna",
    listingType: "FOR_SALE",
    propertyType: "CONDOMINIUM",
    titleEn: "One-bedroom condo for sale, Jemo",
    descriptionEn:
      "Fifty-four square metres on the second floor of a 20/80 block. This is entry-level ownership in Addis and the price is what makes it interesting: less than half what the same floor area costs in CMC. The road in is poor and the commute is long. Those are the trade-offs.",
    price: 4600000,
    negotiable: true,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 54,
    furnishing: "UNFURNISHED",
    area: "jemo",
    addressNote: "Jemo two, 20/80 site",
    amenities: ["water-tank", "gated-compound", "electricity-meter"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 23,
    createdDaysAgo: 29,
    views: 411,
    contactReveals: 34,
  },
  {
    ref: "BT-2004",
    lister: "gojo",
    listingType: "FOR_SALE",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom condo for sale, Lideta, renovated",
    descriptionEn:
      "Renovated top to bottom eighteen months ago and lived in carefully since. Seventy-eight square metres, second floor, with a parking space on the title. Lideta is central without being expensive, and the light rail is a ten-minute walk.",
    price: 11200000,
    negotiable: false,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 78,
    furnishing: "SEMI_FURNISHED",
    area: "lideta",
    addressNote: "Lideta condominium, block C",
    amenities: ["generator", "water-tank", "parking", "security-guard", "furnished-kitchen", "hot-water", "electricity-meter"],
    photos: ["block", "living", "kitchen", "bathroom"],
    confirmedDaysAgo: 2,
    createdDaysAgo: 8,
    views: 738,
    contactReveals: 57,
  },
  {
    ref: "BT-2005",
    lister: "selam",
    listingType: "FOR_SALE",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom condo for sale, Koye Feche",
    descriptionEn:
      "Recent handover, never occupied. Seventy square metres, fourth floor, no lift. The site is still filling up and the infrastructure is catching up with the buildings. Bought as an investment and sold as one: it will be worth more when the road is finished.",
    price: 5400000,
    negotiable: true,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 70,
    furnishing: "UNFURNISHED",
    area: "koye-feche",
    addressNote: "Koye Feche, phase one",
    amenities: ["water-tank", "gated-compound", "electricity-meter", "water-meter"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 27,
    createdDaysAgo: 30,
    views: 289,
    contactReveals: 20,
  },

  // ---------------------------------------------------------------- Apartments
  {
    ref: "BT-2006",
    lister: "addislocator",
    listingType: "FOR_SALE",
    propertyType: "APARTMENT",
    titleEn: "Three-bedroom apartment for sale, Bole Medhanialem",
    descriptionEn:
      "One hundred and sixty square metres on the eighth floor of a building finished in 2024. Two lifts, a full-load generator, an underground reserve, and a basement parking bay on the title. This is prime Bole pricing and the per-square-metre figure is in line with the street.",
    price: 42000000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 160,
    furnishing: "UNFURNISHED",
    area: "bole-medhanialem",
    addressNote: "Off the Medhanialem main road",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "hot-water", "balcony", "wheelchair-accessible"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom"],
    confirmedDaysAgo: 1,
    createdDaysAgo: 11,
    views: 1341,
    contactReveals: 96,
  },
  {
    ref: "BT-2007",
    lister: "zewde",
    listingType: "FOR_SALE",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment for sale, Kazanchis",
    descriptionEn:
      "One hundred and twenty square metres in a Kazanchis tower, sold with the furniture if the buyer wants it. The rental yield here is the best in the city because the corporate tenants never leave. Currently let, and the tenancy can be assigned.",
    price: 28000000,
    negotiable: true,
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 120,
    furnishing: "FURNISHED",
    area: "kazanchis",
    addressNote: "Kazanchis, near the Radisson",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "furnished-kitchen", "hot-water", "balcony"],
    photos: ["block", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 6,
    createdDaysAgo: 18,
    views: 967,
    contactReveals: 72,
  },
  {
    ref: "BT-2008",
    lister: "eyob",
    listingType: "FOR_SALE",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment for sale, Gerji",
    descriptionEn:
      "Ninety-two square metres on the third floor, in a block of twelve built in 2021. Gerji sits between the Bole prices and the CMC prices and this is priced squarely in the middle. Generator, tank, and a parking space.",
    price: 16500000,
    negotiable: true,
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 92,
    furnishing: "UNFURNISHED",
    area: "gerji",
    addressNote: "Gerji Mebrat Hail",
    amenities: ["generator", "water-tank", "parking", "security-guard", "hot-water", "balcony", "electricity-meter"],
    photos: ["block", "living", "kitchen", "bedroom"],
    confirmedDaysAgo: 12,
    createdDaysAgo: 22,
    views: 587,
    contactReveals: 44,
  },
  {
    ref: "BT-2009",
    lister: "tigist",
    listingType: "FOR_SALE",
    propertyType: "APARTMENT",
    titleEn: "Penthouse apartment for sale, Old Airport",
    descriptionEn:
      "Two hundred and forty square metres on the top two floors, with a private terrace and a view over the old runway. Four bedrooms, all en suite. Priced in dollars because the buyers for this are almost entirely diaspora. Serious enquiries only.",
    price: 480000,
    currency: "USD",
    negotiable: true,
    bedrooms: 4,
    bathrooms: 4,
    areaSqm: 240,
    furnishing: "SEMI_FURNISHED",
    area: "old-airport",
    addressNote: "Old Airport, near the international school",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "furnished-kitchen", "hot-water", "balcony", "service-quarter"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom"],
    confirmedDaysAgo: 3,
    createdDaysAgo: 14,
    views: 1088,
    contactReveals: 68,
  },
  {
    ref: "BT-2010",
    lister: "solomon",
    listingType: "FOR_SALE",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment for sale, Megenagna",
    descriptionEn:
      "Eighty-eight square metres, fourth floor, lift in the building. Walking distance to the Megenagna interchange, which is why it will always let. The block is ten years old and the common areas show it, but the flat itself was redone last year.",
    price: 13800000,
    negotiable: true,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 88,
    furnishing: "UNFURNISHED",
    area: "megenagna",
    addressNote: "Megenagna, behind the interchange",
    amenities: ["water-tank", "elevator", "parking", "security-guard", "hot-water", "electricity-meter"],
    photos: ["block", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 17,
    createdDaysAgo: 25,
    views: 493,
    contactReveals: 33,
  },
  {
    ref: "BT-2011",
    lister: "bereket",
    listingType: "FOR_SALE",
    propertyType: "APARTMENT",
    titleEn: "One-bedroom apartment for sale, Ayat",
    descriptionEn:
      "Sixty square metres, ground floor, with a small private yard at the back that is unusual for an apartment. Suits a first-time buyer or someone who wants a rental unit that will not sit empty. Ayat rents reliably even if it does not appreciate fast.",
    price: 7200000,
    negotiable: true,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 60,
    furnishing: "UNFURNISHED",
    area: "ayat",
    addressNote: "Ayat, near the roundabout",
    amenities: ["water-tank", "garden", "gated-compound", "parking", "electricity-meter", "water-meter"],
    photos: ["block", "living", "bedroom", "compound"],
    confirmedDaysAgo: 21,
    createdDaysAgo: 27,
    views: 356,
    contactReveals: 25,
  },

  // ---------------------------------------------------------------- Villas
  {
    ref: "BT-2012",
    lister: "gojo",
    listingType: "FOR_SALE",
    propertyType: "VILLA",
    titleEn: "G+2 villa for sale, Bole Japan",
    titleAm: "ጂ+2 ቪላ ለሽያጭ፣ ቦሌ ጃፓን",
    descriptionEn:
      "Four hundred and ten square metres of house on a 600 square metre plot. Five bedrooms, a family room, a double garage, and a separate two-room service quarter. Built in 2019 and maintained properly since. Full generator, borehole, and a walled compound with a guard house.",
    price: 78000000,
    negotiable: true,
    bedrooms: 5,
    bathrooms: 4,
    areaSqm: 410,
    floorsGPlus: 2,
    furnishing: "UNFURNISHED",
    area: "bole-japan",
    addressNote: "Bole Japan, behind Medhanialem",
    amenities: ["generator", "water-tank", "parking", "security-guard", "service-quarter", "garden", "gated-compound", "internet", "hot-water", "furnished-kitchen"],
    photos: ["houseExterior", "living", "bedroom", "kitchen", "compound"],
    confirmedDaysAgo: 5,
    createdDaysAgo: 19,
    views: 1204,
    contactReveals: 81,
  },
  {
    ref: "BT-2013",
    lister: "yohannes",
    listingType: "FOR_SALE",
    propertyType: "VILLA",
    titleEn: "G+1 house for sale, CMC",
    descriptionEn:
      "Two hundred and twenty square metres over two floors on a 400 square metre plot. Four bedrooms, three bathrooms, and a garden that has been planted for twenty years. My parents built it and we are selling after they moved to my sister in Hawassa. Title is clean and in one name.",
    price: 32000000,
    negotiable: true,
    bedrooms: 4,
    bathrooms: 3,
    areaSqm: 220,
    floorsGPlus: 1,
    furnishing: "UNFURNISHED",
    area: "cmc",
    addressNote: "CMC, near the church",
    amenities: ["water-tank", "parking", "gated-compound", "security-guard", "garden", "service-quarter", "hot-water", "electricity-meter"],
    photos: ["houseExterior", "living", "bedroom", "compound"],
    confirmedDaysAgo: 8,
    createdDaysAgo: 20,
    views: 823,
    contactReveals: 59,
  },
  {
    ref: "BT-2014",
    lister: "addislocator",
    listingType: "FOR_SALE",
    propertyType: "VILLA",
    titleEn: "Luxury villa for sale, Old Airport",
    descriptionEn:
      "Five hundred and eighty square metres on a walled plot of a thousand, in the diplomatic pocket. Six bedrooms, a formal dining room, staff accommodation for three, and a garden with mature jacaranda. This is the top of the Addis market and it transacts in dollars.",
    price: 1150000,
    currency: "USD",
    negotiable: true,
    bedrooms: 6,
    bathrooms: 6,
    areaSqm: 580,
    floorsGPlus: 1,
    furnishing: "UNFURNISHED",
    area: "old-airport",
    addressNote: "Old Airport, diplomatic quarter",
    amenities: ["generator", "water-tank", "parking", "security-guard", "service-quarter", "garden", "gated-compound", "internet", "hot-water", "furnished-kitchen", "wheelchair-accessible"],
    photos: ["houseExterior", "living", "bedroom", "kitchen", "bathroom", "compound"],
    confirmedDaysAgo: 2,
    createdDaysAgo: 13,
    views: 1567,
    contactReveals: 74,
  },
  {
    ref: "BT-2015",
    lister: "meseret",
    listingType: "FOR_SALE",
    propertyType: "VILLA",
    titleEn: "G+1 house for sale, Ayat",
    descriptionEn:
      "One hundred and ninety square metres on a 300 square metre plot. Three bedrooms up, living and kitchen down, with a yard at the front for two cars. Finished in 2022 and never let out. Ayat prices are still reasonable and this is a solid family house.",
    price: 18500000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 190,
    floorsGPlus: 1,
    furnishing: "UNFURNISHED",
    area: "ayat",
    addressNote: "Ayat, past the condominium site",
    amenities: ["water-tank", "parking", "gated-compound", "garden", "hot-water", "electricity-meter", "water-meter"],
    photos: ["houseExterior", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 15,
    createdDaysAgo: 24,
    views: 612,
    contactReveals: 46,
  },
  {
    ref: "BT-2016",
    lister: "zewde",
    listingType: "FOR_SALE",
    propertyType: "VILLA",
    titleEn: "G+3 house for sale, Summit",
    descriptionEn:
      "Three hundred and sixty square metres over four levels, which is a lot of stairs and a lot of house. Six bedrooms, roof terrace, and a lift shaft built in but no lift fitted. Suits a large family or someone who wants to run the top floors as apartments.",
    price: 46000000,
    negotiable: true,
    bedrooms: 6,
    bathrooms: 4,
    areaSqm: 360,
    floorsGPlus: 3,
    furnishing: "UNFURNISHED",
    area: "summit",
    addressNote: "Summit, off the main road",
    amenities: ["generator", "water-tank", "parking", "security-guard", "gated-compound", "balcony", "service-quarter", "hot-water"],
    photos: ["houseExterior", "living", "bedroom", "compound"],
    confirmedDaysAgo: 19,
    createdDaysAgo: 26,
    views: 471,
    contactReveals: 30,
  },
  {
    ref: "BT-2017",
    lister: "rahel",
    listingType: "FOR_SALE",
    propertyType: "VILLA",
    titleEn: "Old G+0 house on a large plot, Kolfe",
    descriptionEn:
      "The house is old and would need gutting, but the plot is 520 square metres in an area that is being rebuilt street by street. Most buyers at this price are looking at the land rather than the building. Sold as it stands, with the title deed in order.",
    price: 12000000,
    negotiable: true,
    bedrooms: 3,
    bathrooms: 1,
    areaSqm: 120,
    floorsGPlus: 0,
    furnishing: "UNFURNISHED",
    area: "kolfe",
    addressNote: "Kolfe, off the Jimma road",
    amenities: ["water-tank", "gated-compound", "garden", "parking"],
    photos: ["houseExterior", "compound", "living"],
    confirmedDaysAgo: 25,
    createdDaysAgo: 30,
    views: 338,
    contactReveals: 24,
  },

  // ---------------------------------------------------------------- Land
  {
    ref: "BT-2018",
    lister: "mulugeta",
    listingType: "FOR_SALE",
    propertyType: "LAND",
    titleEn: "Residential plot for sale, Koye Feche, 250 square metres",
    descriptionEn:
      "Two hundred and fifty square metres with a lease certificate, cleared and pegged. Water and power are at the road. Building permission for G+2 is straightforward on this site because the neighbours have already done it. Sold with all documents.",
    price: 8750000,
    negotiable: true,
    areaSqm: 250,
    area: "koye-feche",
    addressNote: "Koye Feche, near the new access road",
    amenities: ["electricity-meter", "water-meter"],
    photos: ["land"],
    confirmedDaysAgo: 11,
    createdDaysAgo: 23,
    views: 402,
    contactReveals: 28,
  },
  {
    ref: "BT-2019",
    lister: "eyob",
    listingType: "FOR_SALE",
    propertyType: "LAND",
    titleEn: "Plot for sale, Tulu Dimtu, 400 square metres",
    descriptionEn:
      "Four hundred square metres on the Akaky side, walled on three sides. Flat, no rock, and the access road was surfaced last year. This is an area people buy into and hold rather than build on immediately.",
    price: 11600000,
    negotiable: true,
    areaSqm: 400,
    area: "tulu-dimtu",
    addressNote: "Tulu Dimtu, on the Akaky road",
    amenities: ["gated-compound"],
    photos: ["land"],
    confirmedDaysAgo: 20,
    createdDaysAgo: 28,
    views: 267,
    contactReveals: 15,
  },
  {
    ref: "BT-2020",
    lister: "solomon",
    listingType: "FOR_SALE",
    propertyType: "LAND",
    titleEn: "Commercial plot for sale, Lebu, 700 square metres",
    descriptionEn:
      "Seven hundred square metres with road frontage on two sides, zoned for commercial use. The Lebu corridor has been developing quickly since the ring road link opened. Suits a fuel station, a showroom, or a mixed-use block.",
    price: 42000000,
    negotiable: true,
    areaSqm: 700,
    area: "lebu",
    addressNote: "Lebu, corner plot on the ring road link",
    amenities: ["electricity-meter", "water-meter"],
    photos: ["land"],
    confirmedDaysAgo: 7,
    createdDaysAgo: 17,
    views: 519,
    contactReveals: 36,
  },

  // ---------------------------------------------------------------- Whole buildings
  {
    ref: "BT-2021",
    lister: "gojo",
    listingType: "FOR_SALE",
    propertyType: "WHOLE_BUILDING",
    titleEn: "G+6 mixed-use building for sale, Bole Rwanda",
    descriptionEn:
      "Three thousand two hundred square metres of lettable area over seven levels, with retail on the ground floor and offices above. Fully tenanted and producing income from day one. Two lifts, a 300 kVA generator, and basement parking for thirty cars.",
    price: 210000000,
    negotiable: true,
    areaSqm: 3200,
    floorsGPlus: 6,
    area: "bole-rwanda",
    addressNote: "Bole Rwanda, on the main road",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "wheelchair-accessible"],
    photos: ["block", "office", "shop"],
    confirmedDaysAgo: 4,
    createdDaysAgo: 15,
    views: 734,
    contactReveals: 38,
  },
  {
    ref: "BT-2022",
    lister: "zewde",
    listingType: "FOR_SALE",
    propertyType: "WHOLE_BUILDING",
    titleEn: "G+4 apartment building for sale, Gurd Shola",
    descriptionEn:
      "Ten two-bedroom apartments over five levels, eight of them currently let. Sold as a going concern with the tenancies in place. Shared generator and underground tank. The yield is the reason to buy it, not the finishing, which is functional rather than smart.",
    price: 88000000,
    negotiable: true,
    areaSqm: 1150,
    floorsGPlus: 4,
    area: "gurd-shola",
    addressNote: "Gurd Shola, off the ring road",
    amenities: ["generator", "water-tank", "parking", "security-guard", "electricity-meter", "water-meter"],
    photos: ["block", "living", "compound"],
    confirmedDaysAgo: 14,
    createdDaysAgo: 24,
    views: 428,
    contactReveals: 22,
  },

  // ---------------------------------------------------------------- Commercial
  {
    ref: "BT-2023",
    lister: "dawit",
    listingType: "FOR_SALE",
    propertyType: "SHOP",
    titleEn: "Shop for sale, Merkato, Dubai Tera",
    descriptionEn:
      "Sixteen square metres with a roller shutter, freehold on the unit rather than a lease. Merkato units almost never come up for sale; when they do it is usually a family settling an estate. Currently let to an electronics trader who would like to stay.",
    price: 9200000,
    negotiable: true,
    areaSqm: 16,
    area: "merkato",
    addressNote: "Dubai Tera, ground floor",
    amenities: ["security-guard", "electricity-meter"],
    photos: ["shop"],
    confirmedDaysAgo: 16,
    createdDaysAgo: 25,
    views: 386,
    contactReveals: 27,
  },
  {
    ref: "BT-2024",
    lister: "addislocator",
    listingType: "FOR_SALE",
    propertyType: "OFFICE",
    titleEn: "Office floor for sale, Kazanchis",
    descriptionEn:
      "One hundred and eighty square metres, whole floor, sold with the partitions and the cabling in place. Kazanchis office space holds its value better than anywhere else in the city because the tenant pool is corporate and international. Two parking bays on the title.",
    price: 54000000,
    negotiable: true,
    areaSqm: 180,
    furnishing: "SEMI_FURNISHED",
    area: "kazanchis",
    addressNote: "Kazanchis, near the Ministry of Finance",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "wheelchair-accessible"],
    photos: ["office", "block"],
    confirmedDaysAgo: 10,
    createdDaysAgo: 21,
    views: 445,
    contactReveals: 29,
  },
  {
    ref: "BT-2025",
    lister: "mulugeta",
    listingType: "FOR_SALE",
    propertyType: "WAREHOUSE",
    titleEn: "Warehouse for sale, Kality, 900 square metres",
    descriptionEn:
      "Nine hundred square metres under roof on a 1,400 square metre plot, with a concrete apron and a gate wide enough for a forty-foot container. Three-phase power already connected. Close enough to the dry port to matter, far enough out that the land was affordable when it was bought.",
    price: 68000000,
    negotiable: true,
    areaSqm: 900,
    area: "kality",
    addressNote: "Kality, near the dry port",
    amenities: ["security-guard", "parking", "water-tank", "gated-compound", "electricity-meter"],
    photos: ["warehouse"],
    confirmedDaysAgo: 22,
    createdDaysAgo: 29,
    views: 231,
    contactReveals: 13,
  },
];
