import type { ListingSeed } from "./listing-seed";

/**
 * 55 rental listings.
 *
 * Prices are anchored to 2026 Addis market reporting rather than invented.
 * The market splits in two and both halves are represented: a local ETB market
 * where an outer-zone condo is 12,000-25,000 birr and a mid-range apartment is
 * 25,000-70,000, and a diaspora-facing market priced in USD where a furnished
 * two-bedroom in Bole runs 1,200-3,600 dollars. Service quarters sit far below
 * both, which is why they are the only thing a single earner can actually take.
 *
 * lastConfirmedAt is spread deliberately across all three freshness bands so
 * the badge is visible in the grid without anyone having to backdate a row.
 */
export const RENT_LISTINGS: ListingSeed[] = [
  // ---------------------------------------------------------------- Condominiums
  {
    ref: "BT-1001",
    lister: "abebe",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom 40/60 condo on the fourth floor, Ayat",
    titleAm: "ባለ ሁለት መኝታ ኮንዶሚኒየም፣ አያት",
    descriptionEn:
      "Fourth-floor unit in the 40/60 site behind the Ayat roundabout. The block has a shared generator that covers the stairwell and the water pump, so the tank refills even during a cut. Tiled throughout, kitchen cabinets already fitted, and the balcony faces away from the main road. Three months advance, and I will not go below that.",
    price: 26000,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 78,
    furnishing: "UNFURNISHED",
    area: "ayat",
    addressNote: "40/60 site behind the Ayat roundabout",
    amenities: ["generator", "water-tank", "parking", "gated-compound", "electricity-meter", "water-meter"],
    photos: ["block", "living", "kitchen", "bedroom"],
    confirmedDaysAgo: 2,
    createdDaysAgo: 9,
    views: 412,
    contactReveals: 38,
  },
  {
    ref: "BT-1002",
    lister: "dawit",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "One-bedroom 20/80 condo, Jemo one",
    descriptionEn:
      "Ground-floor one-bedroom in Jemo. Cheap because it is far out and the road in gets bad in the rains, but the compound is quiet and there is a water reserve on the roof. Suits one person or a couple who commute toward Mexico. Owner wants six months upfront.",
    price: 14000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 52,
    furnishing: "UNFURNISHED",
    area: "jemo",
    addressNote: "Jemo one, near the condominium clinic",
    amenities: ["water-tank", "gated-compound", "electricity-meter"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 15,
    createdDaysAgo: 24,
    views: 205,
    contactReveals: 11,
  },
  {
    ref: "BT-1003",
    lister: "tigist",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Three-bedroom condo with lift, Summit Safari",
    descriptionEn:
      "Sixth floor with a working lift, which is the reason this one is priced above the rest of the block. Big living room, separate dining, and a service balcony off the kitchen. Building has a generator and its own borehole, so water is not a problem here the way it is further up the hill.",
    price: 48000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 112,
    furnishing: "SEMI_FURNISHED",
    area: "summit",
    addressNote: "Safari area, off the Summit main road",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "balcony", "internet"],
    photos: ["block", "living", "kitchen", "bedroom", "bathroom"],
    confirmedDaysAgo: 4,
    createdDaysAgo: 18,
    views: 631,
    contactReveals: 52,
  },
  {
    ref: "BT-1004",
    lister: "solomon",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom condo, Koye Feche, brand new block",
    descriptionEn:
      "New handover in Koye Feche. Nothing has been lived in yet: the tiles are still boxed in the second bedroom and the owner will finish them before anyone moves in. Very far out, and you need your own transport or a lot of patience with the Kality line. Priced accordingly.",
    price: 12500,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 68,
    furnishing: "UNFURNISHED",
    area: "koye-feche",
    addressNote: "Koye Feche phase two",
    amenities: ["water-tank", "gated-compound", "electricity-meter", "water-meter"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 24,
    createdDaysAgo: 29,
    views: 148,
    contactReveals: 6,
  },
  {
    ref: "BT-1005",
    lister: "hanna",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom condo near Gurd Shola light rail",
    titleAm: "ባለ ሁለት መኝታ ኮንዶ፣ ጉርድ ሾላ",
    descriptionEn:
      "Second floor, ten minutes on foot to the Gurd Shola station. The block is older so the paint is tired, but the plumbing was redone last year and there is a 2,000 litre tank per line. Good for someone working around Megenagna who does not want to sit in traffic every morning.",
    price: 29000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 74,
    furnishing: "UNFURNISHED",
    area: "gurd-shola",
    addressNote: "Behind the Total station on the ring road",
    amenities: ["water-tank", "parking", "security-guard", "electricity-meter", "hot-water"],
    photos: ["block", "living", "kitchen", "bedroom"],
    confirmedDaysAgo: 6,
    createdDaysAgo: 12,
    views: 388,
    contactReveals: 29,
  },
  {
    ref: "BT-1006",
    lister: "bereket",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Studio condo, Tulu Dimtu",
    descriptionEn:
      "Single studio unit on the third floor. Shared water tank for the block and a meter of its own for electricity, so you only pay for what you burn. This is the cheapest thing I have on my books and it goes quickly every time it comes free.",
    price: 9500,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 38,
    furnishing: "UNFURNISHED",
    area: "tulu-dimtu",
    addressNote: "Tulu Dimtu condominium site",
    amenities: ["water-tank", "electricity-meter"],
    photos: ["block", "living"],
    confirmedDaysAgo: 19,
    createdDaysAgo: 26,
    views: 267,
    contactReveals: 21,
  },
  {
    ref: "BT-1007",
    lister: "gojo",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Renovated two-bedroom condo, Lideta",
    descriptionEn:
      "The whole unit was stripped and redone in January: new floor, new kitchen, new bathroom fittings, new wiring. Lideta puts you a short drive from Mexico and Merkato without paying Bole prices. Building has a generator on the ground floor shared between four blocks.",
    price: 34000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 80,
    furnishing: "UNFURNISHED",
    area: "lideta",
    addressNote: "Lideta condominium, block C",
    amenities: ["generator", "water-tank", "parking", "security-guard", "furnished-kitchen", "hot-water", "electricity-meter"],
    photos: ["block", "living", "kitchen", "bathroom"],
    confirmedDaysAgo: 1,
    createdDaysAgo: 7,
    views: 522,
    contactReveals: 47,
  },
  {
    ref: "BT-1008",
    lister: "eyob",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom condo, Kolfe, ground floor with small yard",
    descriptionEn:
      "Ground floor, which in this block means you get the strip of yard behind the unit. Someone has already planted it. No lift needed, no stairs to carry water up when the pump is off. Kolfe is not fashionable but the price reflects that honestly.",
    price: 18500,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 70,
    furnishing: "UNFURNISHED",
    area: "kolfe",
    addressNote: "Kolfe condominium, near the health centre",
    amenities: ["water-tank", "garden", "gated-compound", "electricity-meter", "water-meter"],
    photos: ["block", "living", "bedroom", "compound"],
    confirmedDaysAgo: 11,
    createdDaysAgo: 21,
    views: 231,
    contactReveals: 14,
  },
  {
    ref: "BT-1009",
    lister: "meseret",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Furnished two-bedroom condo, CMC Michael",
    descriptionEn:
      "Fully furnished and ready to walk into: beds, sofa, dining table, fridge, cooker, and a washing machine that works. I am renting it out while I am abroad for two years, so I would rather have one careful tenant for the whole period than turn it over every six months.",
    price: 42000,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 82,
    furnishing: "FURNISHED",
    area: "cmc",
    addressNote: "CMC Michael, behind the church",
    amenities: ["generator", "water-tank", "parking", "security-guard", "furnished-kitchen", "internet", "hot-water", "balcony"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom"],
    confirmedDaysAgo: 3,
    createdDaysAgo: 14,
    views: 704,
    contactReveals: 61,
  },
  {
    ref: "BT-1010",
    lister: "selam",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Three-bedroom condo, Ayer Tena",
    descriptionEn:
      "Corner unit so it takes light from two sides, which matters in these blocks. Three bedrooms is unusual at this price anywhere closer in. The compound gate is manned at night. Water comes on a schedule here, hence the tank, and the owner has never let it run dry.",
    price: 24000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 3,
    bathrooms: 1,
    areaSqm: 92,
    furnishing: "UNFURNISHED",
    area: "ayer-tena",
    addressNote: "Ayer Tena, off the Jimma road",
    amenities: ["water-tank", "gated-compound", "security-guard", "parking", "electricity-meter"],
    photos: ["block", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 27,
    createdDaysAgo: 30,
    views: 176,
    contactReveals: 9,
  },
  {
    ref: "BT-1011",
    lister: "zewde",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "Two-bedroom condo, Signal, close to the ring road",
    descriptionEn:
      "Fifth floor, no lift, which is the trade for the price. Once you are up there the view over Signal is worth something and the noise from the ring road does not reach. Freshly painted last month. Water tank per riser and the block generator covers lighting only, not sockets.",
    price: 27500,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 72,
    furnishing: "UNFURNISHED",
    area: "signal",
    addressNote: "Signal, near the ring road junction",
    amenities: ["generator", "water-tank", "security-guard", "electricity-meter", "balcony"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 8,
    createdDaysAgo: 16,
    views: 349,
    contactReveals: 24,
  },
  {
    ref: "BT-1012",
    lister: "yohannes",
    listingType: "FOR_RENT",
    propertyType: "CONDOMINIUM",
    titleEn: "One-bedroom condo, Lebu, with parking space",
    descriptionEn:
      "Small but well kept, and it comes with a numbered parking space in the compound, which most units in this block do not have. Suits one person. I live in the same building so anything that breaks gets fixed the same week.",
    price: 15500,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 48,
    furnishing: "UNFURNISHED",
    area: "lebu",
    addressNote: "Lebu condominium, block 14",
    amenities: ["parking", "water-tank", "gated-compound", "electricity-meter", "water-meter"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 5,
    createdDaysAgo: 11,
    views: 294,
    contactReveals: 26,
  },

  // ---------------------------------------------------------------- Apartments
  {
    ref: "BT-1013",
    lister: "addislocator",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Furnished two-bedroom apartment, Bole Medhanialem",
    descriptionEn:
      "Walking distance to Edna Mall and the Medhanialem church. Fully furnished to a standard that will suit someone arriving from abroad: proper beds, a real sofa, a working dishwasher. Building generator carries the whole apartment, not just the lights, and there is a 10,000 litre reserve underground. Priced in dollars because that is who takes these.",
    price: 2100,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 118,
    furnishing: "FURNISHED",
    area: "bole-medhanialem",
    addressNote: "Behind Edna Mall, off Cameroon Street",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "furnished-kitchen", "hot-water", "balcony"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom"],
    confirmedDaysAgo: 1,
    createdDaysAgo: 6,
    views: 1284,
    contactReveals: 143,
  },
  {
    ref: "BT-1014",
    lister: "gojo",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Three-bedroom apartment, Old Airport, diplomatic quarter",
    descriptionEn:
      "In the Old Airport pocket where most of the neighbours are embassy staff. Three bedrooms, two of them en suite, and a separate maid's room off the kitchen. Twenty-four hour guard on the compound gate, not just a night watchman. This is the top of the local market and the price says so.",
    price: 3200,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 186,
    furnishing: "FURNISHED",
    area: "old-airport",
    addressNote: "Old Airport, near the Japanese embassy road",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "service-quarter", "internet", "furnished-kitchen", "hot-water", "garden"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom", "compound"],
    confirmedDaysAgo: 2,
    createdDaysAgo: 10,
    views: 941,
    contactReveals: 88,
  },
  {
    ref: "BT-1015",
    lister: "dawit",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment, Gerji, generator and tank",
    titleAm: "ባለ ሁለት መኝታ አፓርታማ፣ ገርጂ",
    descriptionEn:
      "Second floor in a small block of six. The landlord installed a generator two years ago after the neighbourhood spent a week in the dark, and it runs the whole flat. Water tank on the roof plus a ground reserve. Nothing fancy inside, but it works, and in Gerji that is the thing people actually ask about.",
    price: 38000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 88,
    furnishing: "UNFURNISHED",
    area: "gerji",
    addressNote: "Gerji Mebrat Hail, second turn after the school",
    amenities: ["generator", "water-tank", "parking", "gated-compound", "electricity-meter", "hot-water"],
    photos: ["block", "living", "kitchen", "bedroom"],
    confirmedDaysAgo: 4,
    createdDaysAgo: 13,
    views: 618,
    contactReveals: 55,
  },
  {
    ref: "BT-1016",
    lister: "hanna",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "One-bedroom apartment, Kazanchis, walk to the UN",
    descriptionEn:
      "Small one-bedroom aimed squarely at someone working at ECA or one of the agencies around Kazanchis. You can walk to work in fifteen minutes. Furnished lightly: bed, wardrobe, table, no clutter. Generator and lift in the building.",
    price: 52000,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 62,
    furnishing: "SEMI_FURNISHED",
    area: "kazanchis",
    addressNote: "Kazanchis, behind the ECA compound",
    amenities: ["generator", "water-tank", "elevator", "security-guard", "internet", "hot-water"],
    photos: ["block", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 9,
    createdDaysAgo: 19,
    views: 487,
    contactReveals: 41,
  },
  {
    ref: "BT-1017",
    lister: "abebe",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment, Megenagna, one month advance only",
    descriptionEn:
      "I am asking one month advance instead of the usual three, because I would rather have a tenant I can talk to than the largest deposit. Clean two-bedroom on the third floor, walking distance to the Megenagna taxi terminal and the light rail. Water tank, no generator, and I will not pretend otherwise.",
    price: 32000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 1,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 76,
    furnishing: "UNFURNISHED",
    area: "megenagna",
    addressNote: "Megenagna, off the road to Hayahulet",
    amenities: ["water-tank", "parking", "security-guard", "electricity-meter", "water-meter", "balcony"],
    photos: ["block", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 0,
    createdDaysAgo: 4,
    views: 833,
    contactReveals: 96,
  },
  {
    ref: "BT-1018",
    lister: "zewde",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Furnished one-bedroom, Bole Rwanda, short walk to the airport road",
    descriptionEn:
      "Compact and finished properly. Marble in the bathroom, fitted kitchen, air conditioning in the bedroom. Popular with people in and out of the country every few weeks who want somewhere they can lock up and leave. Generator carries the flat.",
    price: 1250,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 70,
    furnishing: "FURNISHED",
    area: "bole-rwanda",
    addressNote: "Bole Rwanda, near the Rwanda embassy turn",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "furnished-kitchen", "hot-water"],
    photos: ["block", "living", "bedroom", "bathroom"],
    confirmedDaysAgo: 12,
    createdDaysAgo: 22,
    views: 566,
    contactReveals: 44,
  },
  {
    ref: "BT-1019",
    lister: "solomon",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Three-bedroom apartment, Haya Hulet",
    descriptionEn:
      "Whole third floor of a small block, so no shared landing. Three bedrooms, big kitchen, and a balcony that runs the length of the flat. The owner is a family who moved to Adama and want a long tenancy. Six months advance is firm.",
    price: 55000,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 132,
    furnishing: "UNFURNISHED",
    area: "haya-hulet",
    addressNote: "Haya Hulet, behind the Bel Air building",
    amenities: ["generator", "water-tank", "parking", "security-guard", "balcony", "hot-water", "electricity-meter"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom"],
    confirmedDaysAgo: 17,
    createdDaysAgo: 25,
    views: 402,
    contactReveals: 31,
  },
  {
    ref: "BT-1020",
    lister: "addislocator",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment, Bisrate Gebriel",
    descriptionEn:
      "Bisrate Gebriel sits between Sarbet and Old Airport and rents like it. This one is a good compromise: proper finishing, secure compound, generator, but not the dollar pricing you get two streets north. Long-term tenants only.",
    price: 78000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 104,
    furnishing: "SEMI_FURNISHED",
    area: "bisrate-gebriel",
    addressNote: "Off South Africa Street",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "hot-water", "furnished-kitchen"],
    photos: ["block", "living", "kitchen", "bedroom", "bathroom"],
    confirmedDaysAgo: 6,
    createdDaysAgo: 15,
    views: 597,
    contactReveals: 49,
  },
  {
    ref: "BT-1021",
    lister: "eyob",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment, Sarbet",
    descriptionEn:
      "Quiet street off the Sarbet main road, five minutes from the Ethiopian Airlines head office. The block is fifteen years old and it shows in places, but the bones are good and the landlord keeps on top of repairs. Parking for one car inside the gate.",
    price: 46000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 90,
    furnishing: "UNFURNISHED",
    area: "sarbet",
    addressNote: "Sarbet, near the Swedish clinic turn",
    amenities: ["water-tank", "parking", "gated-compound", "security-guard", "hot-water", "electricity-meter"],
    photos: ["block", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 20,
    createdDaysAgo: 27,
    views: 318,
    contactReveals: 19,
  },
  {
    ref: "BT-1022",
    lister: "selam",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "One-bedroom apartment, Urael",
    descriptionEn:
      "Behind the Urael church, so you are inside the Bole road corridor without paying for a Bole address. One bedroom, decent light, and the building has a lift that actually works. No generator, which is why it is not more.",
    price: 36000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 58,
    furnishing: "UNFURNISHED",
    area: "urael",
    addressNote: "Behind Urael church",
    amenities: ["water-tank", "elevator", "security-guard", "electricity-meter", "hot-water"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 3,
    createdDaysAgo: 8,
    views: 445,
    contactReveals: 37,
  },
  {
    ref: "BT-1023",
    lister: "gojo",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Furnished three-bedroom, Bole Atlas",
    descriptionEn:
      "Top floor of an Atlas-area block with a terrace you can actually use. Furnished throughout and let with the furniture. There is a generator, a borehole, and a guard on the gate day and night. Twelve months advance is what the owner wants and it is not negotiable.",
    price: 3400,
    currency: "USD",
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 12,
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 210,
    furnishing: "FURNISHED",
    area: "bole-atlas",
    addressNote: "Atlas area, near the Hilton turn",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "furnished-kitchen", "hot-water", "balcony", "service-quarter"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom"],
    confirmedDaysAgo: 5,
    createdDaysAgo: 20,
    views: 1102,
    contactReveals: 79,
  },
  {
    ref: "BT-1024",
    lister: "bereket",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment, Kotebe",
    descriptionEn:
      "Kotebe is quiet and green and a long way from anything if you do not drive. Two bedrooms, small garden shared with the ground-floor tenant, and a compound gate. Good value if your work is out this side of town.",
    price: 22000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 74,
    furnishing: "UNFURNISHED",
    area: "kotebe",
    addressNote: "Kotebe, near the teachers college",
    amenities: ["water-tank", "garden", "gated-compound", "parking", "electricity-meter"],
    photos: ["block", "living", "bedroom", "compound"],
    confirmedDaysAgo: 23,
    createdDaysAgo: 28,
    views: 189,
    contactReveals: 12,
  },
  {
    ref: "BT-1025",
    lister: "tigist",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment, Bole Michael",
    descriptionEn:
      "Bole Michael is busy and loud and very well connected. This flat faces the courtyard rather than the street, which makes the difference. Two bedrooms, fitted kitchen, and a water tank that the landlord tops up by bowser when the mains fail.",
    price: 30000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 72,
    furnishing: "UNFURNISHED",
    area: "bole-michael",
    addressNote: "Bole Michael, behind the mosque",
    amenities: ["water-tank", "parking", "security-guard", "furnished-kitchen", "electricity-meter"],
    photos: ["block", "living", "kitchen", "bedroom"],
    confirmedDaysAgo: 7,
    createdDaysAgo: 17,
    views: 361,
    contactReveals: 28,
  },
  {
    ref: "BT-1026",
    lister: "dawit",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Studio apartment, Piassa",
    descriptionEn:
      "Single room with a kitchenette and its own bathroom, in one of the old buildings above the Piassa shops. High ceilings, wooden floor, and a window onto the street. It is not modern and it is not quiet, but nowhere else in the city looks like this.",
    price: 17000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 42,
    furnishing: "SEMI_FURNISHED",
    area: "piassa",
    addressNote: "Piassa, above the shops on Adwa Avenue",
    amenities: ["water-tank", "electricity-meter", "hot-water"],
    photos: ["block", "living", "bedroom"],
    confirmedDaysAgo: 14,
    createdDaysAgo: 23,
    views: 512,
    contactReveals: 40,
  },
  {
    ref: "BT-1027",
    lister: "mulugeta",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Two-bedroom apartment, Torhailoch",
    descriptionEn:
      "New block finished last year, so everything in it is new: wiring, plumbing, fittings. Torhailoch has improved a lot since the ring road went through. Generator and underground tank shared by the building, both maintained under contract rather than by whoever remembers.",
    price: 40000,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 96,
    furnishing: "UNFURNISHED",
    area: "torhailoch",
    addressNote: "Torhailoch, off the ring road",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "hot-water", "balcony"],
    photos: ["block", "living", "kitchen", "bedroom", "bathroom"],
    confirmedDaysAgo: 2,
    createdDaysAgo: 5,
    views: 673,
    contactReveals: 58,
  },
  {
    ref: "BT-1028",
    lister: "zewde",
    listingType: "FOR_RENT",
    propertyType: "APARTMENT",
    titleEn: "Furnished two-bedroom, Kazanchis tower",
    descriptionEn:
      "Eleventh floor with a view across to the Sheraton. Two bedrooms, both en suite, furnished to hotel standard, and the building has two lifts and a full-load generator. Serviced weekly if you want it at extra cost. Corporate lets welcome.",
    price: 2600,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 140,
    furnishing: "FURNISHED",
    area: "kazanchis",
    addressNote: "Kazanchis, near the Radisson",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "furnished-kitchen", "hot-water", "balcony", "wheelchair-accessible"],
    photos: ["block", "living", "bedroom", "kitchen", "bathroom"],
    confirmedDaysAgo: 10,
    createdDaysAgo: 21,
    views: 878,
    contactReveals: 66,
  },

  // ---------------------------------------------------------------- Villas
  {
    ref: "BT-1029",
    lister: "gojo",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "G+1 villa with garden, Old Airport",
    titleAm: "ጂ+1 ቪላ ከአትክልት ቦታ ጋር፣ ኦልድ አየርፖርት",
    descriptionEn:
      "Four bedrooms over two floors on a 500 square metre plot, with a mature garden and a separate service quarter at the back. The kind of house that gets taken by an embassy or an NGO country director. Standby generator, borehole, and a guard house at the gate.",
    price: 4200,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 4,
    bathrooms: 3,
    areaSqm: 320,
    floorsGPlus: 1,
    furnishing: "SEMI_FURNISHED",
    area: "old-airport",
    addressNote: "Old Airport, near the international school",
    amenities: ["generator", "water-tank", "parking", "security-guard", "service-quarter", "garden", "internet", "hot-water", "gated-compound", "furnished-kitchen"],
    photos: ["houseExterior", "living", "bedroom", "kitchen", "compound"],
    confirmedDaysAgo: 1,
    createdDaysAgo: 12,
    views: 1156,
    contactReveals: 102,
  },
  {
    ref: "BT-1030",
    lister: "yohannes",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "G+0 three-bedroom house, CMC",
    descriptionEn:
      "Single-storey house in a walled compound with room for two cars and a small lawn. Three bedrooms, one bathroom, and an outside kitchen as well as the inside one, which older houses out here often have. Family let preferred.",
    price: 95000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 180,
    floorsGPlus: 0,
    furnishing: "UNFURNISHED",
    area: "cmc",
    addressNote: "CMC, near the roundabout",
    amenities: ["water-tank", "parking", "gated-compound", "security-guard", "garden", "service-quarter", "electricity-meter", "water-meter"],
    photos: ["houseExterior", "living", "bedroom", "kitchen", "compound"],
    confirmedDaysAgo: 8,
    createdDaysAgo: 18,
    views: 542,
    contactReveals: 43,
  },
  {
    ref: "BT-1031",
    lister: "addislocator",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "G+2 villa, Bole Japan, five bedrooms",
    descriptionEn:
      "Large modern house over three levels in the Japan pocket behind Bole Medhanialem. Five bedrooms, four bathrooms, family room on the top floor, and a basement that the current tenant uses as a gym. Full-load generator and a 15,000 litre underground tank.",
    price: 5500,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 12,
    bedrooms: 5,
    bathrooms: 4,
    areaSqm: 420,
    floorsGPlus: 2,
    furnishing: "FURNISHED",
    area: "bole-japan",
    addressNote: "Bole Japan, behind Medhanialem",
    amenities: ["generator", "water-tank", "parking", "security-guard", "service-quarter", "garden", "internet", "hot-water", "gated-compound", "furnished-kitchen", "balcony"],
    photos: ["houseExterior", "living", "bedroom", "kitchen", "bathroom", "compound"],
    confirmedDaysAgo: 4,
    createdDaysAgo: 16,
    views: 987,
    contactReveals: 71,
  },
  {
    ref: "BT-1032",
    lister: "meseret",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "G+1 house, Ayat, four bedrooms",
    descriptionEn:
      "Four bedrooms upstairs, living and kitchen down, with a yard big enough for children to play in. Ayat is far but it is calm, and the school run is short if you use the ones on this side. There is a tank but no generator; the owner is open to installing one for a longer lease.",
    price: 62000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 4,
    bathrooms: 2,
    areaSqm: 240,
    floorsGPlus: 1,
    furnishing: "UNFURNISHED",
    area: "ayat",
    addressNote: "Ayat, past the condominium site",
    amenities: ["water-tank", "parking", "gated-compound", "garden", "service-quarter", "electricity-meter", "water-meter"],
    photos: ["houseExterior", "living", "bedroom", "compound"],
    confirmedDaysAgo: 16,
    createdDaysAgo: 24,
    views: 386,
    contactReveals: 27,
  },
  {
    ref: "BT-1033",
    lister: "solomon",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "G+1 villa, Summit, furnished",
    descriptionEn:
      "Furnished four-bedroom in one of the newer Summit compounds. Everything works and everything is under two years old. Shared compound facilities including a guard and a generator that covers all four houses. Suits a family arriving from abroad who do not want to buy furniture.",
    price: 2900,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 4,
    bathrooms: 3,
    areaSqm: 280,
    floorsGPlus: 1,
    furnishing: "FURNISHED",
    area: "summit",
    addressNote: "Summit, inside a four-house compound",
    amenities: ["generator", "water-tank", "parking", "security-guard", "garden", "internet", "furnished-kitchen", "hot-water", "gated-compound"],
    photos: ["houseExterior", "living", "bedroom", "kitchen", "compound"],
    confirmedDaysAgo: 11,
    createdDaysAgo: 20,
    views: 604,
    contactReveals: 48,
  },
  {
    ref: "BT-1034",
    lister: "rahel",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "Old G+0 house with big compound, Kebena",
    descriptionEn:
      "This is a 1970s house and it has not been modernised. Three bedrooms, one bathroom, cement floors, and a compound of nearly 600 square metres with eucalyptus at the back. Cheap for what it is because it needs work. I would rather someone lived in it than let it sit empty.",
    price: 34000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 3,
    bathrooms: 1,
    areaSqm: 150,
    floorsGPlus: 0,
    furnishing: "UNFURNISHED",
    area: "kebena",
    addressNote: "Kebena, up from the river bridge",
    amenities: ["water-tank", "gated-compound", "garden", "parking", "service-quarter"],
    photos: ["houseExterior", "living", "compound", "bedroom"],
    confirmedDaysAgo: 26,
    createdDaysAgo: 30,
    views: 297,
    contactReveals: 22,
  },
  {
    ref: "BT-1035",
    lister: "zewde",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "G+2 villa, Gerji, six bedrooms, suits an office",
    descriptionEn:
      "Six bedrooms over three floors, which for a family is a lot and for an NGO or a small company is exactly right. Parking for six cars inside the compound. Already wired for a network and there is a generator sized for the whole building.",
    price: 180000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    bedrooms: 6,
    bathrooms: 4,
    areaSqm: 460,
    floorsGPlus: 2,
    furnishing: "UNFURNISHED",
    area: "gerji",
    addressNote: "Gerji, near the Imperial hotel road",
    amenities: ["generator", "water-tank", "parking", "security-guard", "gated-compound", "internet", "service-quarter", "garden"],
    photos: ["houseExterior", "office", "living", "compound"],
    confirmedDaysAgo: 13,
    createdDaysAgo: 22,
    views: 458,
    contactReveals: 35,
  },
  {
    ref: "BT-1036",
    lister: "eyob",
    listingType: "FOR_RENT",
    propertyType: "VILLA",
    titleEn: "G+1 villa, Jacros, three bedrooms",
    descriptionEn:
      "Newly built on the Jacros side, still smelling of paint. Three bedrooms, two bathrooms, open-plan living and kitchen downstairs. The compound is small but the house is efficient. Water tank fitted, generator not.",
    price: 48000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 175,
    floorsGPlus: 1,
    furnishing: "UNFURNISHED",
    area: "jacros",
    addressNote: "Jacros, off the Yerer Goro road",
    amenities: ["water-tank", "parking", "gated-compound", "hot-water", "electricity-meter", "water-meter"],
    photos: ["houseExterior", "living", "bedroom", "kitchen"],
    confirmedDaysAgo: 5,
    createdDaysAgo: 9,
    views: 521,
    contactReveals: 46,
  },

  // ---------------------------------------------------------------- Service quarters
  {
    ref: "BT-1037",
    lister: "tigist",
    listingType: "FOR_RENT",
    propertyType: "SERVICE_QUARTER",
    titleEn: "Service quarter in a family compound, Kotebe",
    titleAm: "ሰርቪስ ቤት፣ ኮተቤ",
    descriptionEn:
      "One room with its own door, in the compound of a family house. Shared toilet and shower in the yard. Water and light are included in the rent because there is no separate meter. Quiet compound, gate locked at ten. Suitable for one person.",
    price: 4500,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 1,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 16,
    furnishing: "UNFURNISHED",
    area: "kotebe",
    addressNote: "Kotebe, inside a family compound",
    amenities: ["water-tank", "gated-compound"],
    photos: ["compound", "bedroom"],
    confirmedDaysAgo: 3,
    createdDaysAgo: 10,
    views: 673,
    contactReveals: 84,
  },
  {
    ref: "BT-1038",
    lister: "mulugeta",
    listingType: "FOR_RENT",
    propertyType: "SERVICE_QUARTER",
    titleEn: "Service quarter with private shower, Kolfe",
    descriptionEn:
      "Better than most: this one has its own shower and toilet rather than sharing with the compound. Single room, painted last month, with a small window. Electricity is on the main house meter and I charge a flat 400 birr a month for it, no arguments either way.",
    price: 5500,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 1,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 20,
    furnishing: "UNFURNISHED",
    area: "kolfe",
    addressNote: "Kolfe, behind the main house",
    amenities: ["water-tank", "gated-compound", "hot-water"],
    photos: ["compound", "bedroom", "bathroom"],
    confirmedDaysAgo: 6,
    createdDaysAgo: 14,
    views: 498,
    contactReveals: 62,
  },
  {
    ref: "BT-1039",
    lister: "abebe",
    listingType: "FOR_RENT",
    propertyType: "SERVICE_QUARTER",
    titleEn: "Service quarter, Ayer Tena, water always available",
    descriptionEn:
      "The compound has a 5,000 litre tank and a pump, so there is water even in the weeks the mains are off, which out here is most weeks. Room is bare, floor is cement, and the rent is low because of it. Shared washing area.",
    price: 3800,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 1,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 14,
    furnishing: "UNFURNISHED",
    area: "ayer-tena",
    addressNote: "Ayer Tena, shared compound",
    amenities: ["water-tank", "gated-compound"],
    photos: ["compound", "bedroom"],
    confirmedDaysAgo: 18,
    createdDaysAgo: 26,
    views: 331,
    contactReveals: 39,
  },
  {
    ref: "BT-1040",
    lister: "selam",
    listingType: "FOR_RENT",
    propertyType: "SERVICE_QUARTER",
    titleEn: "Two service rooms let together, Shiro Meda",
    descriptionEn:
      "Two adjoining rooms in the same compound, let as one. Works for a couple or for someone who needs a room to work in as well as sleep. Shiro Meda is walkable to Sidist Kilo and the university. Shared toilet, own water tap in the yard.",
    price: 7000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 1,
    bedrooms: 2,
    bathrooms: 1,
    areaSqm: 28,
    furnishing: "UNFURNISHED",
    area: "shiro-meda",
    addressNote: "Shiro Meda, up from the market",
    amenities: ["water-tank", "gated-compound", "electricity-meter"],
    photos: ["compound", "bedroom"],
    confirmedDaysAgo: 21,
    createdDaysAgo: 28,
    views: 276,
    contactReveals: 31,
  },
  {
    ref: "BT-1041",
    lister: "rahel",
    listingType: "FOR_RENT",
    propertyType: "SERVICE_QUARTER",
    titleEn: "Service quarter, Lafto, own electricity meter",
    descriptionEn:
      "Rare for a service room: it has its own electricity meter, so you pay the utility directly and nobody argues about the bill at the end of the month. One room, cement floor, tin roof with a ceiling board fitted. Toilet shared with one other room.",
    price: 4200,
    negotiable: false,
    rentPeriod: "MONTHLY",
    advanceMonths: 1,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 15,
    furnishing: "UNFURNISHED",
    area: "lafto",
    addressNote: "Lafto, near the condominium site",
    amenities: ["electricity-meter", "water-tank", "gated-compound"],
    photos: ["compound", "bedroom"],
    confirmedDaysAgo: 9,
    createdDaysAgo: 17,
    views: 402,
    contactReveals: 47,
  },
  {
    ref: "BT-1042",
    lister: "bereket",
    listingType: "FOR_RENT",
    propertyType: "SERVICE_QUARTER",
    titleEn: "Service quarter, Hana Mariam",
    descriptionEn:
      "Single room in a compound of four. The landlord lives on site. No hot water and no shower inside the room, but the compound tap runs most days and there is a tank for when it does not. Cheapest room I have in this area.",
    price: 3200,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 1,
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 12,
    furnishing: "UNFURNISHED",
    area: "hana-mariam",
    addressNote: "Hana Mariam, compound of four rooms",
    amenities: ["water-tank", "gated-compound"],
    photos: ["compound", "bedroom"],
    confirmedDaysAgo: 25,
    createdDaysAgo: 29,
    views: 214,
    contactReveals: 25,
  },

  // ---------------------------------------------------------------- Shops
  {
    ref: "BT-1043",
    lister: "dawit",
    listingType: "FOR_RENT",
    propertyType: "SHOP",
    titleEn: "Shop on the main road, Bole Medhanialem",
    descriptionEn:
      "Forty square metres of frontage directly on the Medhanialem road, with a roller shutter and a mezzanine for stock. Foot traffic here is as good as it gets in Addis. Twelve months advance, which for a commercial let on this road is standard.",
    price: 110000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 12,
    areaSqm: 40,
    area: "bole-medhanialem",
    addressNote: "On the Medhanialem main road",
    amenities: ["generator", "water-tank", "security-guard", "parking", "internet", "electricity-meter"],
    photos: ["shop", "office"],
    confirmedDaysAgo: 2,
    createdDaysAgo: 11,
    views: 728,
    contactReveals: 54,
  },
  {
    ref: "BT-1044",
    lister: "solomon",
    listingType: "FOR_RENT",
    propertyType: "SHOP",
    titleEn: "Shop in Merkato, Dubai Tera",
    titleAm: "ሱቅ በመርካቶ፣ ዱባይ ተራ",
    descriptionEn:
      "Small unit in the Dubai Tera section, mostly used for electronics and phone accessories at the moment. Twelve square metres, roller shutter, and a shared store room at the back of the building. Merkato rents are quoted per month but everyone pays a year up front.",
    price: 28000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 12,
    areaSqm: 12,
    area: "merkato",
    addressNote: "Dubai Tera, second floor",
    amenities: ["security-guard", "electricity-meter"],
    photos: ["shop"],
    confirmedDaysAgo: 12,
    createdDaysAgo: 21,
    views: 383,
    contactReveals: 30,
  },
  {
    ref: "BT-1045",
    lister: "hanna",
    listingType: "FOR_RENT",
    propertyType: "SHOP",
    titleEn: "Corner shop, Megenagna",
    descriptionEn:
      "Corner unit at a junction, so two sides of glass. Currently a pharmacy, fitted out with shelving that the next tenant can keep or strip. Generator backup for the whole building, which matters if you are keeping anything cold.",
    price: 65000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 32,
    area: "megenagna",
    addressNote: "Megenagna, corner of the ring road",
    amenities: ["generator", "water-tank", "parking", "security-guard", "electricity-meter"],
    photos: ["shop", "office"],
    confirmedDaysAgo: 19,
    createdDaysAgo: 25,
    views: 291,
    contactReveals: 18,
  },
  {
    ref: "BT-1046",
    lister: "eyob",
    listingType: "FOR_RENT",
    propertyType: "SHOP",
    titleEn: "Small shop, Piassa",
    descriptionEn:
      "Ground-floor unit on a Piassa side street. Eighteen square metres with a small back room. Rent is low for a central location because the street is quieter than Adwa Avenue. Suits a tailor, a barber, or a small café.",
    price: 22000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 18,
    area: "piassa",
    addressNote: "Piassa, side street off Adwa Avenue",
    amenities: ["water-tank", "electricity-meter", "water-meter"],
    photos: ["shop"],
    confirmedDaysAgo: 28,
    createdDaysAgo: 30,
    views: 167,
    contactReveals: 8,
  },

  // ---------------------------------------------------------------- Offices
  {
    ref: "BT-1047",
    lister: "gojo",
    listingType: "FOR_RENT",
    propertyType: "OFFICE",
    titleEn: "Office floor, Kazanchis, 220 square metres",
    descriptionEn:
      "Whole fourth floor, open plan with two partitioned meeting rooms already built. Fibre is already in the building. Full-load generator and two lifts. Kazanchis is where the agencies and the corporates want to be, and the rent reflects it.",
    price: 240000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 220,
    area: "kazanchis",
    addressNote: "Kazanchis, near the Ministry of Finance",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "wheelchair-accessible", "hot-water"],
    photos: ["office", "block"],
    confirmedDaysAgo: 3,
    createdDaysAgo: 13,
    views: 445,
    contactReveals: 33,
  },
  {
    ref: "BT-1048",
    lister: "zewde",
    listingType: "FOR_RENT",
    propertyType: "OFFICE",
    titleEn: "Two-room office, Bole Rwanda",
    descriptionEn:
      "Sixty square metres split into two rooms and a reception area, on the second floor of a small commercial building. Good for a consultancy or a travel agency. Parking for two cars is included, which on this street is worth having.",
    price: 78000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 60,
    area: "bole-rwanda",
    addressNote: "Bole Rwanda, above the bank",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet"],
    photos: ["office"],
    confirmedDaysAgo: 7,
    createdDaysAgo: 15,
    views: 312,
    contactReveals: 21,
  },
  {
    ref: "BT-1049",
    lister: "addislocator",
    listingType: "FOR_RENT",
    propertyType: "OFFICE",
    titleEn: "Office suite, Bole Atlas, fitted",
    descriptionEn:
      "Comes fitted: desks, chairs, cabling, and a server cupboard with its own cooling. The previous tenant was a software company that outgrew it. One hundred and ten square metres on the sixth floor with a view down the Atlas road.",
    price: 1400,
    currency: "USD",
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 110,
    furnishing: "FURNISHED",
    area: "bole-atlas",
    addressNote: "Atlas area, sixth floor",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "hot-water", "wheelchair-accessible"],
    photos: ["office", "block"],
    confirmedDaysAgo: 15,
    createdDaysAgo: 23,
    views: 388,
    contactReveals: 26,
  },
  {
    ref: "BT-1050",
    lister: "selam",
    listingType: "FOR_RENT",
    propertyType: "OFFICE",
    titleEn: "Single office room, Mexico",
    descriptionEn:
      "One room of thirty square metres in a shared building near Mexico Square. Reception and toilets are shared with the other tenants. This is a starter office, priced for someone who has just registered a business and does not want to work from home any more.",
    price: 26000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 3,
    areaSqm: 30,
    area: "mexico",
    addressNote: "Mexico, near the square",
    amenities: ["water-tank", "elevator", "security-guard", "internet", "electricity-meter"],
    photos: ["office"],
    confirmedDaysAgo: 22,
    createdDaysAgo: 27,
    views: 203,
    contactReveals: 12,
  },

  // ---------------------------------------------------------------- Warehouses
  {
    ref: "BT-1051",
    lister: "mulugeta",
    listingType: "FOR_RENT",
    propertyType: "WAREHOUSE",
    titleEn: "Warehouse, Kality, 600 square metres",
    descriptionEn:
      "Six hundred square metres under a steel roof with a concrete floor rated for forklifts, plus a yard that a container lorry can turn in. Close to the Kality dry port, which is the whole point of being out here. Three-phase power and a night guard.",
    price: 220000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 600,
    area: "kality",
    addressNote: "Kality, near the dry port",
    amenities: ["security-guard", "parking", "water-tank", "gated-compound", "electricity-meter"],
    photos: ["warehouse"],
    confirmedDaysAgo: 5,
    createdDaysAgo: 19,
    views: 256,
    contactReveals: 17,
  },
  {
    ref: "BT-1052",
    lister: "yohannes",
    listingType: "FOR_RENT",
    propertyType: "WAREHOUSE",
    titleEn: "Store and yard, Lebu",
    descriptionEn:
      "Three hundred square metres of covered store plus about the same again as open yard, walled and gated. Used for building materials by the last tenant. The access road is unsurfaced but a truck can get in.",
    price: 95000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 300,
    area: "lebu",
    addressNote: "Lebu, off the industrial road",
    amenities: ["gated-compound", "security-guard", "water-tank", "electricity-meter"],
    photos: ["warehouse"],
    confirmedDaysAgo: 20,
    createdDaysAgo: 26,
    views: 181,
    contactReveals: 10,
  },

  // ---------------------------------------------------------------- Whole buildings
  {
    ref: "BT-1053",
    lister: "zewde",
    listingType: "FOR_RENT",
    propertyType: "WHOLE_BUILDING",
    titleEn: "G+5 commercial building, Bole Michael",
    descriptionEn:
      "Whole building available on one lease: ground floor retail, four office floors above, and a basement car park. Two lifts, a 250 kVA generator, and an underground water reserve. Currently half occupied and the owner will deliver it vacant.",
    price: 1250000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 12,
    areaSqm: 2400,
    floorsGPlus: 5,
    area: "bole-michael",
    addressNote: "Bole Michael, on the main road",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "internet", "wheelchair-accessible"],
    photos: ["block", "office", "shop"],
    confirmedDaysAgo: 10,
    createdDaysAgo: 20,
    views: 341,
    contactReveals: 19,
  },
  {
    ref: "BT-1054",
    lister: "gojo",
    listingType: "FOR_RENT",
    propertyType: "WHOLE_BUILDING",
    titleEn: "G+4 building, Gurd Shola, suits a school or clinic",
    descriptionEn:
      "Purpose-built with wide corridors and large rooms, which makes it awkward as offices and ideal as a school, a college, or a clinic. Lift to all floors, ramp at the entrance, and parking for fifteen cars. Long lease preferred.",
    price: 620000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 12,
    areaSqm: 1600,
    floorsGPlus: 4,
    area: "gurd-shola",
    addressNote: "Gurd Shola, off the ring road",
    amenities: ["generator", "water-tank", "elevator", "parking", "security-guard", "wheelchair-accessible", "internet"],
    photos: ["block", "office"],
    confirmedDaysAgo: 24,
    createdDaysAgo: 29,
    views: 228,
    contactReveals: 11,
  },

  // ---------------------------------------------------------------- Land
  {
    ref: "BT-1055",
    lister: "mulugeta",
    listingType: "FOR_RENT",
    propertyType: "LAND",
    titleEn: "Walled plot for lease, Tulu Dimtu, 800 square metres",
    descriptionEn:
      "Eight hundred square metres, walled and gated, currently empty. Leased as a yard rather than for building: the last tenant parked lorries on it, the one before stored timber. Water and a power connection are already at the gate.",
    price: 85000,
    negotiable: true,
    rentPeriod: "MONTHLY",
    advanceMonths: 6,
    areaSqm: 800,
    area: "tulu-dimtu",
    addressNote: "Tulu Dimtu, on the Akaky road",
    amenities: ["gated-compound", "security-guard", "electricity-meter", "water-meter"],
    photos: ["land"],
    confirmedDaysAgo: 14,
    createdDaysAgo: 24,
    views: 143,
    contactReveals: 7,
  },
];
